USE newdb;

CREATE TABLE IF NOT EXISTS `responses` (
`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`uniqueID` VARCHAR(100) NOT NULL,
`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`session` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q1` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q2` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q3` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q4` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q5` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q6` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q7` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q8` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q9` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q10` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q11` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q12` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q13` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q14` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q15` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q16` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q17` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q18` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q19` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q20` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q21` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q22` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q23` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q24` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q25` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q26` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q27` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q28` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q29` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q30` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q31` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q32` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q33` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q34` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q35` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q36` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q37` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q38` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q39` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`q40` TINYINT UNSIGNED NOT NULL DEFAULT 0,
CONSTRAINT ppSession UNIQUE (uniqueID,session)
);

CREATE TABLE IF NOT EXISTS people (
`uniqueID` VARCHAR(100) NOT NULL,
`email` VARCHAR(100), 
`rType` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`session` TINYINT UNSIGNED NOT NULL DEFAULT 0,
CONSTRAINT ppSession UNIQUE (uniqueID,session)
);

CREATE TABLE IF NOT EXISTS userComments (commentList VARCHAR(2000));
